
CREATE TABLE infobuffer(id INTEGER PRIMARY KEY AUTOINCREMENT,type VARCHAR(100),dateTime VARCHAR(30),registNo VARCHAR(30));
CREATE TABLE infobufferContent(id integer primary key AUTOINCREMENT,infobufferId INTEGER,xmlContent VARCHAR(600));
CREATE TABLE UploadInfo_Tbl(id integer primary key,plate_no VARCHAR(100),policy_no VARCHAR(100),state VARCHAR(100),parcent VARCHAR(100),file_size VARCHAR(100),action VARCHAR(100),file_url VARCHAR(100));


CREATE TABLE POLICYINFO(id integer primary key,REGISTNO VARCHAR(30),INSURENAME  VARCHAR(100), DRIVINGLICENSEOWNER VARCHAR(100),LICENSENO VARCHAR(30),LABELTYPE VARCHAR(30),VINNO VARCHAR(100),ENGINENO VARCHAR(100),CARFIRSTREGISTRATION VARCHAR(50),USEYEARS VARCHAR(10),NEWCARPURCHASEPRICE VARCHAR(30),VEHICLEUSE VARCHAR(30),QSPOLICYNO VARCHAR(100),QSPOLICYINSUREDATE VARCHAR(100),BUSINESSPOLICYNO VARCHAR(100),BUSINESSPOLICYINSUREDATE VARCHAR(100),BASICCLAUSETYPES VARCHAR(30),POLICYCOMCODE VARCHAR(30),BUSINESSFLAG VARCHAR(10),POLICYENDORSES VARCHAR(10));

CREATE TABLE ITEMKIND(id integer primary key,POLICYID INTEGER,ITEMKINDCODE VARCHAR(100),ITEMKINDAMOUNT VARCHAR(100));



CREATE TABLE IF NOT EXISTS checktask(registno TEXT PRIMARY KEY,latitude REAL,longitude REAL,linkername TEXT, linkerphoneno TEXT, reportorname TEXT, reportorphoneno TEXT,insuredname TEXT,insuredphoneno TEXT,inputedate TEXT, surveytaskstatus TEXT, applycannelstatus TEXT, synchrostatus TEXT,insrtedname TEXT,licenseno TEXT, isread INTEGER, isaccept INTEGER,createtime TEXT, ordertime TEXT, alarmtime INTEGER, dispatchreason TEXT, iscontact INTEGER,contacttime TEXT, completetime TEXT);
CREATE TABLE IF NOT EXISTS certainlosstask(registno TEXT,itemno INTEGER,itemtype TEXT,latitude REAL,longitude REAL,printnumber INTEGER,linkername TEXT, linkerphoneno TEXT, reportorname TEXT, reportorphoneno TEXT,insuredname TEXT,insuredphoneno TEXT, inputedate TEXT, surveytaskstatus TEXT,verifypassflag TEXT,applycannelstatus TEXT, synchrostatus TEXT,insrtedname TEXT,licenseno TEXT,isread INTEGER, isaccept INTEGER, createtime TEXT, ordertime TEXT, alarmtime INTEGER, dispatchreason TEXT, iscontact INTEGER, contacttime TEXT,completetime TEXT,SERIALNO TEXT,PRIMARY KEY(registno,itemno)); 


CREATE TABLE TASKQUERY(id integer primary key,ACCEPTTIME VARCHAR(30),REGISTNO VARCHAR(22),DAMAGECODE VARCHAR(4),INSRTEDNAME VARCHAR(20),LICENSENO VARCHAR(20),BRANDNAME VARCHAR(100),DISPATCHPTIME VARCHAR(30),REPORTTIME VARCHAR(30),DISPATCHPLACE VARCHAR(100),DRIVERNAME VARCHAR(20),PROMPTMESSAGE VARCHAR(20),DAMAGEDAYP VARCHAR(100),TASKRECEIPTTIME VARCHAR(30),ARRIVESCENETIME VARCHAR(30),LINKCUSTOMTIME VARCHAR(30),TASKHANDTIME VARCHAR(30),FIRSTSITEFLAG VARCHAR(30),DAMAGENAME VARCHAR(100),INDEMNITYDUTY VARCHAR(1),CLAIMTYPE VARCHAR(2),ISCOMMONCLAIM VARCHAR(1),SUBROGATETYPE VARCHAR(1),ACCIDENTBOOK VARCHAR(1),ACCIDENT VARCHAR(1),INSUREDMOBILE VARCHAR(20),ENTRUSTNAME VARCHAR(20),ENTRUSTMOBILE VARCHAR(20),CHECKREPORT VARCHAR(100),SATISFACTION VARCHAR(1),ACCEPTTASKDATE VARCHAR(30),DISPOSETASKDATE VARCHAR(30),REMARK VARCHAR(600),FIRSTPHOTODATE VARCHAR(30),COMPENSATERATE TEXT);
CREATE TABLE TASKCARLOSS(id integer primary key,TASKQUERYID integer,ISEDITED VARCHAR(1), LICENSENO VARCHAR(20),SERIALNO VARCHAR(10),INSURECARFLAG VARCHAR(1),FRAMENO VARCHAR(30),BRANDNAME VARCHAR(100),DUTYPERCENT VARCHAR(20),POLICYNO VARCHAR(22),ENGINENO VARCHAR(22),INSURECOMCODE VARCHAR(120),INSURECOMNAME VARCHAR(20),CARKINDCODE VARCHAR(22),LICENSETYPE VARCHAR(22),NULLDRIVERNAME VARCHAR(20),NULLCERTITYPE VARCHAR(20),NULLDRIVERCODE VARCHAR(20),NULLCERTITYPECODE VARCHAR(20));
CREATE TABLE TASKCHECKEXT(id integer primary key,TASKQUERYID integer,CHECKKERNELNAME VARCHAR(20),CHECKKERNELSELECT VARCHAR(1),CHECKKERNELTYPE VARCHAR(1),CHECKKERNELCODE VARCHAR(200),SERIALNO VARCHAR(10),CHECKEXTREMARK VARCHAR(600));

CREATE TABLE CHECKDRIVER(id integer primary key,TASKQUERYID integer,SERIALNO VARCHAR(22),DRIVINGLICENSENO VARCHAR(22),DRIVERNAME VARCHAR(22),IDENTIFYNUMBER VARCHAR(22),RECEIVELICENSEDATE VARCHAR(30),DRIVERCERTITYPE varchar(30),DRIVERCERTITYPECODE varchar(30));

CREATE TABLE CLAIMBASIC(id integer primary key,REGISTNO VARCHAR(30),HISTORICALACCIDENT VARCHAR(10),HISTORICALCLAIMTIMES VARCHAR(10),HISTORICALCLAIMSUM VARCHAR(20));
CREATE TABLE HISCLAIM(id integer primary key,CLAIMBASICID integer,REGISTNO VARCHAR(30),DAMAGEDATE VARCHAR(30),REGISTDATE VARCHAR(30),DAMAGEADDRESS VARCHAR(100),CLAIMSTATUS VARCHAR(30),CLAIMAMOUNT VARCHAR(30));



CREATE TABLE IF NOT EXISTS DeflossSynchroMain(REGISTNO TEXT,LOSSNO TEXT,LASTUPDATETIME TEXT,SUBMITTYPE TEXT, ESTIMATENO TEXT, KINDCODE TEXT,PLATENO TEXT, VEHKINDCODE TEXT,VEHKINDNAME TEXT,VEHCERTAINCODE TEXT,VEHCERTAINNAME TEXT, VEHGROUPNAME TEXT, VEHGROUPCODE TEXT, VEHSERICODE TEXT,VEHSERINAME TEXT,VEHYEARTYPE TEXT, VEHFACTORYCODE TEXT, VEHFACTORYNAME TEXT,VEHBRANDCODE TEXT, VEHBRANDNAME TEXT,CERTAINHANDLECODE TEXT,CERTAINHANDLENAME TEXT,REPAIRFACTORYCODE TEXT,REPAIRFACTORYNAME TEXT,REPAIRCOOPERATEFLAG TEXT,REPAIRMODE TEXT,REPAIRREASON TEXT,REPAIRAPTITUDE TEXT,SUBROGATETYPE TEXT,EXCESSTYPE TEXT,ACCIDENTBOOK TEXT,ACCIDENT TEXT,INSUREDNAME TEXT,INSUREDMOBILE TEXT,ENTRUSTNAME TEXT,ENTRUSTMOBILE TEXT,SELFCONFIGFLAG TEXT,VERSION TEXT,VEHSERIGRADENAME TEXT,CARREGISTERDATE TEXT,CARVEHICLEDESC TEXT, CARFACTORYCODE TEXT,CARFACTORYNAME TEXT,CLAIMTYPE TEXT,SATISFACTION TEXT, SUMFITSFEE TEXT,SUMREPAIRFEE TEXT,SUMVERIREST TEXT, SUMCERTAINLOSS TEXT,TEXTCONTENT TEXT,  PRIMARY KEY(REGISTNO,LOSSNO));
CREATE TABLE IF NOT EXISTS DeflossSynchroReplace(REGISTNO TEXT,LOSSNO TEXT,PARTID TEXT,SERIALNO TEXT, ORIGINALID TEXT, ORIGINALNAME TEXT, PARTSTANDARDCODE TEXT,PARTSTANDARD TEXT,PARTGROUPCODE TEXT,PARTGROUPNAME TEXT, PRICEMODEL TEXT, SYSTEMPRICE001 TEXT, LOCALPRICE001 TEXT,SYSTEMPRICE002 TEXT,LOCALPRICE002 TEXT, LOSSFEE TEXT, RESTFEE TEXT,SELFCONFIGFLAG TEXT, LOSSCOUNT TEXT, REMARK TEXT, SYSTEMPRICE TEXT, LOCALPRICE TEXT,PRIMARY KEY(REGISTNO,LOSSNO,PARTID,SERIALNO));
CREATE TABLE IF NOT EXISTS DeflossSynchroRepair(REGISTNO TEXT,LOSSNO TEXT,REPAIRID TEXT,SERIALNO TEXT, REPAIRCODE TEXT, REPAIRNAME TEXT, REPAIRITEMCODE TEXT,REPAIRITEMNAME TEXT,REPAIRFEE TEXT,SELFCONFIGFLAG TEXT, PRICEMODEL TEXT,SYSTEMPRICE TEXT,PRIMARY KEY(REGISTNO,LOSSNO,REPAIRID,SERIALNO));


CREATE TABLE PICADDRESS(id integer primary key,REGISTNO VARCHAR(30),LOSSNO VARCHAR(30),PICNAME VARCHAR(30),PICADDRESS VARCHAR(100),REMARK VARCHAR(600),STARTE VARCHAR(1));
CREATE TABLE USERINFO(id integer primary key,USERNAME TEXT,PASSWORD TEXT);

CREATE TABLE GPSADDRESS(id integer primary key,ADDRESS TEXT);

CREATE TABLE IF NOT EXISTS CertainLossMain(REGISTNO TEXT,LOSSNO TEXT,POLICYCOMCODE TEXT,LICENSENO TEXT,BRANDNAME TEXT,DISPATCHPTIME TEXT,REPORTTIME TEXT,OUTOFPLACE TEXT,DRIVERNAME TEXT,PROMPTMESSAGE TEXT,INSUREDNAME TEXT,INSUREDMOBILE TEXT,ENTRUSTNAME TEXT,ENTRUSTMOBILE TEXT,DAMAGEDAYP TEXT, PRIMARY KEY(REGISTNO,LOSSNO));
CREATE TABLE IF NOT EXISTS ClItemKind(REGISTNO TEXT,LOSSNO TEXT, ITEMCODE TEXT,ITEMNAME TEXT,PRIMARY KEY(REGISTNO,LOSSNO,ITEMCODE));
CREATE TABLE IF NOT EXISTS ClCheckRecord(REGISTNO TEXT,LOSSNO TEXT,FIRSTSITEFLAG TEXT,DAMAGECODE TEXT,DAMAGENAME TEXT,INDEMNITYDUTY TEXT,CLAIMTYPE TEXT,ISCOMMONCLAIM TEXT,SUBROGATETYPE TEXT,ACCIDENTBOOK TEXT,ACCIDENT TEXT,REMARK TEXT,CHECKREPORT TEXT,PRIMARY KEY(REGISTNO,LOSSNO));
CREATE TABLE IF NOT EXISTS ClCarInfo(REGISTNO TEXT,LOSSNO TEXT, SERIALNO INTEGER,INSURECARFLAG TEXT,LICENSENO TEXT,DEFINELOSSPERSON TEXT,DEFINELOSSAMOUT TEXT,PRIMARY KEY(REGISTNO,LOSSNO,SERIALNO));
CREATE TABLE IF NOT EXISTS ClTaskInfo(REGISTNO TEXT,LOSSNO TEXT,TASKRECEIPTTIME TEXT,ARRIVESCENETIME TEXT,LINKCUSTOMTIME TEXT,TASKHANDTIME TEXT,PRIMARY KEY(REGISTNO,LOSSNO));
CREATE TABLE IF NOT EXISTS ClObject(REGISTNO TEXT,LOSSNO TEXT,SERIALNO INTEGER,INSURECARFLAG TEXT,LICENSENO TEXT,CARFRAMENO TEXT,BRANDNAME TEXT,NEWPRUCHASEAMOUNT TEXT,CARVEHICLEDESC TEXT,CARFACTORYCODE TEXT,CARFACTORYNAME TEXT,CARREGISTERDATE TEXT,INSUREVEHICODE TEXT,PRIMARY KEY(REGISTNO,LOSSNO,SERIALNO));
CREATE TABLE IF NOT EXISTS ClContent(REGISTNO TEXT,LOSSNO TEXT,REPAIRFACTORYCODE TEXT,REPAIRFACTORYNAME TEXT,REPAIRCOOPERATEFLAG TEXT,REPAIRMODE TEXT,REPAIRAPTITUDE TEXT,DEFLOSSRISKCODE TEXT,SUMFITSFEE TEXT,SUMREPAIRFEE TEXT,SUMREST TEXT,SUMCERTAINLOSS TEXT,SUMCERTAINLOSSCH TEXT,DEFLOSSADVISE TEXT,SATISFIEDDEGREE TEXT,REPAIRREASON TEXT,UNDWRTREMARK TEXT,SHIJIUFEE TEXT,PRIMARY KEY(REGISTNO,LOSSNO));
CREATE TABLE IF NOT EXISTS ClCheckExt(REGISTNO TEXT,LOSSNO TEXT,SERIALNO INTEGER,CHECKKERNELNAME TEXT,CHECKKERNELSELECT TEXT,CHECKKERNELTYPE TEXT,CHECKKERNELCODE TEXT,CHECKEXTREMARK TEXT,PRIMARY KEY(REGISTNO,LOSSNO,SERIALNO));

